version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lmw_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - lmw-network

  backend:
    build: .
    container_name: lmw_django_api
    ports:
      - "8001:8000"
    env_file: .env
    depends_on:
      - db
    networks:
      - lmw-network
    command: ${DJANGO_COMMAND:-python manage.py runserver 0.0.0.0:8000}

  frontend:
    build:
      context: ../ednu-lmw
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: lmw_frontend_ui
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lmw-network

volumes:
  postgres_data:

networks:
  lmw-network:
    driver: bridge