# Generated by Django 5.2.7 on 2025-10-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_molecula', models.CharField(max_length=255)),
                ('smiles', models.CharField(max_length=255, unique=True)),
                ('referencia', models.CharField(max_length=255)),
                ('nome_planta', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=100)),
                ('origem', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
