# Generated by Django 5.2.10 on 2026-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='aromatic_ring_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='formula_molecular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='fraction_csp3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='h_bond_acceptors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='h_bond_donors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='heavy_atom_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='inchi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='inchikey',
            field=models.CharField(blank=True, db_index=True, max_length=27, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='logp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='murcko_scaffold',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='mw_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='mw_exact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='np_likeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='qed_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='ring_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='rotatable_bonds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='smiles_canonical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='tpsa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='smiles',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
