# Generated by Django 5.2.10 on 2026-01-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0002_molecule_aromatic_ring_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='estrutura_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
